### ISSUE TITLE
From Elixir and Actions article

### ISSUE THREAD

**Issue by yordis** [jclem/actions#1]
Hey Jonathan, read your article about Workflows and Elixir, and I am super excited about this.

Since it seems that you work on this at Github I thought would be a good idea to ask you a question.

Can I manage all these workflows from a centralized repository instead of per project bases?

Right now I am managing https://github.com/straw-hat-team, and the cost of maintaining these files from GitHub is getting out of hand, between Travis + Makefile (workflows), Code of Conduct, License, Issues Templates, and PR template, same settings of Collaborations & Team, Branches, Notifications... 

It is tough for one person hero to keep up with this, and increases proportionally to the number of projects.

You get the idea (this is a GitHub issue overall)

So I would love to see these workflows to be handled at the organization level as well instead of everything being per project bases.

Most of my Elixir repositories have the same setup, rare cases I would encounter some individual cases and even so I would prefer to manage it at the Organization level.

### Side note

I am reading your article, super hype.

I went and fork this repo, super excited and create a `main.workflow.` file on my repo aaaaaannnd, 😭  I have to sign up for beta testing, no fair, no fair, now I am crying at 5:30 AM

**Comment by yordis** [comment]
Also, I am sorry if I use Github Issues for this, I clicked About page and tried to look up some contact info so I didn't have to do this, but neither GitHub profile or personal Website has some social media links or something like that.

**Comment by jclem** [comment]
@yordis Really sorry I missed this—I haven't been looking at notifications from this repository!

You can manage actions from a centralized repository, but the workflows currently need to be in the repository for which they're running. I messaged you on Twitter—going to close this and we can follow up more on there.
